### ISSUE TITLE
Use Air formatting

### ISSUE THREAD

**Issue by roaldarbol** [roaldarbol/animovement#112]
Posit has made a formatter called Air, and has an associated CI Action which should be added. It can either check that the code is properly formatted, or automatically format it (makes a new commit). I think we'll start with simply checking, then later on we can always change to active formatting. 

The CI action is:
```yaml
- name: Format R code
  uses: rstudio/shiny-workflows/format-r-code@v1
  with:
    check: true
```

Links:
https://www.tidyverse.org/blog/2025/02/air/#fn:1
https://posit-dev.github.io/air/
https://github.com/rstudio/shiny-workflows/tree/main/format-r-code
